[package]
name = "eth2-pallet-init"
version = "0.1.0"
edition = "2021"

[dependencies]
tree_hash = { path = "../tree_hash", default-features = false }
merkle_proof = { path = "../merkle_proof", default-features = false }
consensus_types = { path = "../consensus_types" }
eth_rpc_client = { path = "../eth_rpc_client" }
eth-types = { path = "../eth-types/", features = ["eth2", "eip1559"]}
log = { version = "0.4", features = ["std", "serde"] }
clap = { version = "3.1.6", features = ["derive"] }
reqwest = { version = "0.11", features = ["blocking"] }
serde_json = "1.0.74"
serde = { version = "1.0", features = ["derive"] }
toml = "0.5.9"
async-trait = "0.1.58"
sp-keyring = { default-features=false, version = "7.0.0" }
sp-core = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.36" }

webb-relayer-utils = { path = "../../../relayer/crates/relayer-utils" }
webb = { path = "../../../webb-rs", features = [
    "evm-runtime",
    "substrate-runtime"
]}
webb-proposals = { path = "../../../webb-rs/proposals" }
tokio = { version = "1.1", features = ["macros", "rt", "time"] }

