[workspace]
members = [
    "pallet",
	"crates/*",
    "eth2substrate-block-relay-rs",
]

[patch.crates-io]
sp-io = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.36" }
sp-core = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.36" }